[global]
    workgroup = WORKGROUP
    server string = ThinkPad

    interfaces = br0
    bind interfaces only = yes
    smb ports = 445

    map to guest = Bad User
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes
    disable netbios = yes
    server role = standalone server
    server services = -dns, -nbt

    ;name resolve order = hosts
    ;log level = 3

[data]
    path = /data/
    browseable = yes
    guest ok = yes
    writeable = Yes
    force user = user
    create mask = 0775
    directory mask = 0755
