export PS1="\n\u@Build:\[\033[01;34m\]\w\[\033[00m\]# "
export DEB_BUILD_OPTIONS="noddebs parallel=7"

# enable color support of ls and also add handy aliases
alias ls='ls --color=auto'
alias ll='ls --color=auto -alF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# debhelper 10|11|12|src|libs repo
function en10 {
    cat > /etc/apt/preferences.d/backports <<EOF
Package: *
Pin: release a=xenial-backports
Pin-Priority: 500
EOF
    cat >> /etc/apt/sources.list <<EOF

deb http://mirrors.tencent.com/ubuntu/ xenial-backports main universe multiverse
EOF
    apt-get update && apt-get -y dist-upgrade
}

function en11 {
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5EDB1B62EC4926EA
    echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/queens main" > /etc/apt/sources.list.d/cloudarchive-queens.list
    echo "deb [trusted=yes] file:/debhelper/11 ./" >> /etc/apt/sources.list.d/debhelper11.list
    apt-get update && apt-get -y dist-upgrade
}

function en12 {
    echo "deb [trusted=yes] file:/debhelper/12 ./" > /etc/apt/sources.list.d/debhelper12.list
    apt-get update && apt-get -y dist-upgrade
}

function enlibs {
    (cd /data/libs/$1 && dpkg-scanpackages -m . > Packages)
    echo "deb [trusted=yes] file:/data/libs/$1 ./" > /etc/apt/sources.list.d/libs-${1%%=*}.list
    apt-get update && apt-get -y dist-upgrade
}

function ensrc {
    > /etc/apt/sources.list.d/all.list
    for rel in yakkety zesty artful cosmic disco eoan; do
    cat >> /etc/apt/sources.list.d/all.list <<EOF
deb-src http://mirrors.ustc.edu.cn/ubuntu-old-releases/ubuntu/ ${rel} main universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu-old-releases/ubuntu/ ${rel}-updates main universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu-old-releases/ubuntu/ ${rel}-backports main universe multiverse
EOF
    done
    for rel in bionic focal groovy hirsute; do
    cat >> /etc/apt/sources.list.d/all.list <<EOF
deb-src http://mirrors.tencent.com/ubuntu/ ${rel} main universe multiverse
deb-src http://mirrors.tencent.com/ubuntu/ ${rel}-updates main universe multiverse
deb-src http://mirrors.tencent.com/ubuntu/ ${rel}-backports main universe multiverse
EOF
    done
    apt-get update
}


# search/build packages from all source repo
function en {
    resp=$(apt-cache madison $1 | awk '{print $1"="$3"\t"$6"\t"$7}' | column -t)

    for rel in hirsute groovy focal eoan disco cosmic bionic artful zesty yakkety xenial;
    do
        for repo in $rel-backports $rel-updates $rel;
        do
            while read line;
            do
                if test -d /data/libs/$(awk '{print $1}' <<<"$line"); then
                    line=$(sed 's/^/*/' <<<"$line")
                else
                    line=$(sed 's/^/ /' <<<"$line")
                fi
                case $rel in
                    hirsute|groovy|focal|bionic)
                        grep " $repo/" <<<"$line"
                        ;;
                    *)
                        echo "$line"
                        ;;
                esac
            done < <(grep " $repo/" <<<"$resp")
        done
    done
}

function bb {
    apt-get -y build-dep $1 || return

    apt-get -qq install libfile-fcntllock-perl

    id build >& /dev/null || useradd -m build
    su - build -c "DEB_BUILD_OPTIONS='noddebs parallel=7' apt-get source -b $1"
    [[ $? -eq 0 ]] && mv /home/build/*.deb . && echo && ls -l *.deb
}


sed -i 's/mirrors.aliyun.com/mirrors.tencent.com/' /etc/apt/sources.list
source /etc/bash_completion
cd ~
ensrc
